### ISSUE TITLE
Incorrect order and naming

### ISSUE THREAD

**Issue by shannoneagle** [wdecoster/nanocomp#59]
In the command, I listed my files in the order I wanted them and provided names for the files in the same order. The summary stats are correct. However, the charts are in alphabetical order (not the order I provided). The labels are correct on the first chart (both data and labels are in alphabetical order). However, the following charts use the name order I provided, but the data is in alphabetical order.

**Comment by wdecoster** [comment]
Thanks for reporting this. Just to make sure, you were using the latest version right?

**Comment by shannoneagle** [comment]
I have version 1.19.0.

**Comment by wdecoster** [comment]
At least some of this problem should be fixed in version 1.19.1 (as reported in https://github.com/wdecoster/nanocomp/issues/58). I have now pushed v1.19.2, which further made sure the order wasn't changed for some plots. I _think_ everything should be alright now, but don't hesitate to let me know if you see further issues.

**Comment by shannoneagle** [comment]
I have updated to v1.19.3. however, I'm still having some issues. All the labels on the plots are now associated with the correct data. However, the first plot (Comparing number of reads) in the report does not show the data in the order I provided.

**Comment by pvdam3** [comment]
I am experiencing this issue for the throughput in bases plot (order is correct, but coloring is different) and number of reads (coloring is the same as the total throughput plot but different from all the other plots, and the order is different than all the other plots). I am using NanoComp 1.24.2

**Comment by wdecoster** [comment]
This should be fixed in v1.25.2 :-)
